#!/bin/bash



VIDEO=~/videos/output`date +%d%m%Y%H%M%S`.mp4
RES=`xdpyinfo | grep dimensions | awk '{print $2}'`
echo Resolucion: $RES

## Capture only desktop
ffmpeg -video_size $RES -framerate 25 -f x11grab -i :0.0 $VIDEO

## Capture Desktoop with audio
# ffmpeg -video_size $RES -framerate 25 -f x11grab -i :0.0 -f pulse -ac 2 -i default $VIDEO